
name: docker based CI
on:  
  pull_request:     

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        mkdir share
        sudo apt-get install -y curl
        docker build -t pymoab .
        docker run -v "$PWD/share:/share"
        curl -s https://codecov.io/bash | bash
