
name: docker based CI
on:  
  pull_request:     

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build -t pymoab .
        docker run --rm pymoab /bin/bash -c "pytest tests && curl -s https://codecov.io/bash | bash"
